name: Bug Report
description: Found a Bug that needs to be fixed?
labels: ["type: Bug Report"]
body:
  - type: markdown
    attributes:
      value: |-
        Please join the [Discord Server](https://discord.gg/ZptCBHeHyg) for questions.
  - type: checkboxes
    attributes:
      label: General
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the Issue-tracker.
          required: true
        - label: I have checked for PRs that might already address this issue.
          required: true
  - type: textarea
    attributes:
      label: "Expected Behaviour"
      description: "What did you expect this website to do?"
      placeholder: "This website should do ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproduction Steps"
      description: |-
        Please add the steps you took to reproduce this problem.  
        Put "N/A" if you don't have a reproducible setup.
      placeholder: |-
        1. Do this.
        2. Do that.
    validations:
      required: true