blank_issues_enabled: false
contact_links:
  - name: Ask on Discord
    url: https://discord.gg/ZptCBHeHyg
    about: Get fast support for your questions in the Discord server.
  - name: Webpage
    url: https://www.casiebarie.dev/other/website/
    about: Find more info about this page on my website.