name: Feature Request
description: Request a new feature.
labels: ["type: Feature Request"]
body:
  - type: markdown
    attributes:
      value: |-
        Please join the [Discord Server](https://discord.gg/ZptCBHeHyg) for questions.
  - type: checkboxes
    attributes:
      label: General
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the Issue-tracker.
          required: true
        - label: I have checked the branches or the maintainers' PRs for upcoming features.
          required: true
  - type: textarea
    attributes:
      label: "Feature Request"
      description: "Provide a small description of the feature you want to have added."
      placeholder: "This website should get ..."
    validations:
      required: true