name: Deploy Jekyll site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        run: bundle exec jekyll build"
        env:
          JEKYLL_ENV: production
      - name: Minify JS/CSS/HTML
        run: |
          npm install -g terser csso-cli html-minifier-terser
          find ./_site -name '*.js' -exec terser {} --compress -o {} \;
          find ./_site -name '*.css' -exec csso {} -o {} \;
          find ./_site -name '*.html' -exec html-minifier-terser \
            --collapse-boolean-attributes \
            --minify-css \
            --minify-js \
            --minify-urls \
            --remove-attribute-quotes \
            --remove-comments \
            {} -o {} \;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-minify
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
